# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtGui, QtWidgets, QtCore
import flask_server
import sys
import requests

class Flask_server_thread(QtCore.QThread):
    port = int(flask_server.os.environ.get("PORT", 5000))
    @QtCore.pyqtSlot()
    def run(self):
        flask_server.app.run(debug=False,host='0.0.0.0',port=self.port)
    @QtCore.pyqtSlot()
    def quit(self):
        requests.get("http://localhost:5000/shutdown")


class Ui_ThermstUtil(QtWidgets.QMainWindow):
    flask_thread=Flask_server_thread()
    def setupUi(self, ThermstUtil):
        ThermstUtil.setObjectName("ThermstUtil")
        ThermstUtil.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(ThermstUtil)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsBox = QtWidgets.QGroupBox(self.centralWidget)
        self.settingsBox.setMinimumSize(QtCore.QSize(300, 0))
        self.settingsBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.settingsBox.setObjectName("settingsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modeSelectorLayout = QtWidgets.QHBoxLayout()
        self.modeSelectorLayout.setObjectName("modeSelectorLayout")
        self.modeSelectorLabel = QtWidgets.QLabel(self.settingsBox)
        self.modeSelectorLabel.setObjectName("modeSelectorLabel")
        self.modeSelectorLayout.addWidget(self.modeSelectorLabel)
        self.modeSelectorHotButton = QtWidgets.QRadioButton(self.settingsBox)
        self.modeSelectorHotButton.setObjectName("modeSelectorHotButton")
        self.modeSelectorLayout.addWidget(self.modeSelectorHotButton)
        self.modeSelectorColdButton = QtWidgets.QRadioButton(self.settingsBox)
        self.modeSelectorColdButton.setChecked(True)
        self.modeSelectorColdButton.setObjectName("modeSelectorColdButton")
        self.modeSelectorLayout.addWidget(self.modeSelectorColdButton)
        self.verticalLayout.addLayout(self.modeSelectorLayout)
        self.setHotTemperatureLayout = QtWidgets.QHBoxLayout()
        self.setHotTemperatureLayout.setObjectName("setHotTemperatureLayout")
        self.hotTemperatureLabel = QtWidgets.QLabel(self.settingsBox)
        self.hotTemperatureLabel.setObjectName("hotTemperatureLabel")
        self.setHotTemperatureLayout.addWidget(self.hotTemperatureLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setHotTemperatureLayout.addItem(spacerItem)
        self.hotTemperatureInputBox = QtWidgets.QSpinBox(self.settingsBox)
        self.hotTemperatureInputBox.setMinimum(-10)
        self.hotTemperatureInputBox.setMaximum(50)
        self.hotTemperatureInputBox.setObjectName("hotTemperatureInputBox")
        self.setHotTemperatureLayout.addWidget(self.hotTemperatureInputBox)
        self.hotTempCelsiusLabel = QtWidgets.QLabel(self.settingsBox)
        self.hotTempCelsiusLabel.setObjectName("hotTempCelsiusLabel")
        self.setHotTemperatureLayout.addWidget(self.hotTempCelsiusLabel)
        self.verticalLayout.addLayout(self.setHotTemperatureLayout)
        self.setColdTemperatureLayout = QtWidgets.QHBoxLayout()
        self.setColdTemperatureLayout.setObjectName("setColdTemperatureLayout")
        self.coldTemperatureLabel = QtWidgets.QLabel(self.settingsBox)
        self.coldTemperatureLabel.setObjectName("coldTemperatureLabel")
        self.setColdTemperatureLayout.addWidget(self.coldTemperatureLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setColdTemperatureLayout.addItem(spacerItem1)
        self.coldTemperatureInputBox = QtWidgets.QSpinBox(self.settingsBox)
        self.coldTemperatureInputBox.setMinimum(-10)
        self.coldTemperatureInputBox.setMaximum(50)
        self.coldTemperatureInputBox.setObjectName("coldTemperatureInputBox")
        self.setColdTemperatureLayout.addWidget(self.coldTemperatureInputBox)
        self.coldTempCelsiusLabel = QtWidgets.QLabel(self.settingsBox)
        self.coldTempCelsiusLabel.setObjectName("coldTempCelsiusLabel")
        self.setColdTemperatureLayout.addWidget(self.coldTempCelsiusLabel)
        self.verticalLayout.addLayout(self.setColdTemperatureLayout)
        self.restorePresetsButton = QtWidgets.QPushButton(self.settingsBox)
        self.restorePresetsButton.setObjectName("restorePresetsButton")
        self.verticalLayout.addWidget(self.restorePresetsButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(self.settingsBox)
        self.startButton.setObjectName("startButton")
        self.startButton.pressed.connect(self.start_flask_server)
        self.verticalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.settingsBox)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.horizontalLayout.addWidget(self.settingsBox)
        self.displayTabs = QtWidgets.QTabWidget(self.centralWidget)
        self.displayTabs.setAutoFillBackground(True)
        self.displayTabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.displayTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.displayTabs.setElideMode(QtCore.Qt.ElideNone)
        self.displayTabs.setObjectName("displayTabs")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logTab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logDisplayBox = QtWidgets.QTextBrowser(self.logTab)
        self.logDisplayBox.setAutoFillBackground(True)
        self.logDisplayBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logDisplayBox.setObjectName("logDisplayBox")
        self.horizontalLayout_3.addWidget(self.logDisplayBox)
        self.displayTabs.addTab(self.logTab, "")
        self.graphTab = QtWidgets.QWidget()
        self.graphTab.setObjectName("graphTab")
        self.displayTabs.addTab(self.graphTab, "")
        self.horizontalLayout.addWidget(self.displayTabs)
        ThermstUtil.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ThermstUtil)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        ThermstUtil.setMenuBar(self.menuBar)
        self.actionStart = QtWidgets.QAction(ThermstUtil)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(ThermstUtil)
        self.actionStop.setObjectName("actionStop")
        self.actionSetHotMode = QtWidgets.QAction(ThermstUtil)
        self.actionSetHotMode.setObjectName("actionSetHotMode")
        self.actionSetColdMode = QtWidgets.QAction(ThermstUtil)
        self.actionSetColdMode.setObjectName("actionSetColdMode")
        self.actionSetHotTemperature = QtWidgets.QAction(ThermstUtil)
        self.actionSetHotTemperature.setObjectName("actionSetHotTemperature")
        self.actionSetColdTemperature = QtWidgets.QAction(ThermstUtil)
        self.actionSetColdTemperature.setObjectName("actionSetColdTemperature")
        self.actionRestorePresets = QtWidgets.QAction(ThermstUtil)
        self.actionRestorePresets.setObjectName("actionRestorePresets")
        self.actionUserManual = QtWidgets.QAction(ThermstUtil)
        self.actionUserManual.setObjectName("actionUserManual")
        self.actionAboutThermstUtil = QtWidgets.QAction(ThermstUtil)
        self.actionAboutThermstUtil.setObjectName("actionAboutThermstUtil")
        self.menuHelp.addAction(self.actionUserManual)
        self.menuHelp.addAction(self.actionAboutThermstUtil)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ThermstUtil)
        self.displayTabs.setCurrentIndex(1)
        self.startButton.clicked.connect(self.actionStart.trigger)
        self.stopButton.clicked.connect(self.actionStop.trigger)
        self.hotTemperatureInputBox.valueChanged['int'].connect(self.actionSetHotTemperature.trigger)
        self.coldTemperatureInputBox.valueChanged['int'].connect(self.actionSetColdTemperature.trigger)
        self.modeSelectorHotButton.clicked.connect(self.actionSetHotMode.trigger)
        self.modeSelectorColdButton.clicked.connect(self.actionSetColdMode.trigger)
        QtCore.QMetaObject.connectSlotsByName(ThermstUtil)

    def retranslateUi(self, ThermstUtil):
        _translate = QtCore.QCoreApplication.translate
        ThermstUtil.setWindowTitle(_translate("ThermstUtil", "MainWindow"))
        self.settingsBox.setTitle(_translate("ThermstUtil", "Settings"))
        self.modeSelectorLabel.setText(_translate("ThermstUtil", "Mode:"))
        self.modeSelectorHotButton.setText(_translate("ThermstUtil", "Hot"))
        self.modeSelectorColdButton.setText(_translate("ThermstUtil", "Cold"))
        self.hotTemperatureLabel.setText(_translate("ThermstUtil", "Hot Temperature:"))
        self.hotTempCelsiusLabel.setText(_translate("ThermstUtil", "ºC"))
        self.coldTemperatureLabel.setText(_translate("ThermstUtil", "Cold Temperature:"))
        self.coldTempCelsiusLabel.setText(_translate("ThermstUtil", "ºC"))
        self.restorePresetsButton.setText(_translate("ThermstUtil", "Restore presets"))
        self.startButton.setText(_translate("ThermstUtil", "Start"))
        self.stopButton.setText(_translate("ThermstUtil", "Stop"))
        self.logDisplayBox.setHtml(_translate("ThermstUtil", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#ff0000;\">Logs are stored in &quot;Logs&quot; folder, named after this application execution time and date</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#000000;\">Connecting...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#000000;\">Conection succesful!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#000000;\">Awaiting comands</span></p></body></html>"))
        self.displayTabs.setTabText(self.displayTabs.indexOf(self.logTab), _translate("ThermstUtil", "Log"))
        self.displayTabs.setTabText(self.displayTabs.indexOf(self.graphTab), _translate("ThermstUtil", "Graph"))
        self.menuHelp.setTitle(_translate("ThermstUtil", "Help"))
        self.actionStart.setText(_translate("ThermstUtil", "Start"))
        self.actionStop.setText(_translate("ThermstUtil", "Stop"))
        self.actionSetHotMode.setText(_translate("ThermstUtil", "Set Hot Mode"))
        self.actionSetHotMode.setToolTip(_translate("ThermstUtil", "Set Hot Mode"))
        self.actionSetColdMode.setText(_translate("ThermstUtil", "Set Cold Mode"))
        self.actionSetColdMode.setToolTip(_translate("ThermstUtil", "Set Cold Mode"))
        self.actionSetHotTemperature.setText(_translate("ThermstUtil", "Set Hot Temperature"))
        self.actionSetHotTemperature.setToolTip(_translate("ThermstUtil", "Set Hot Temperature"))
        self.actionSetColdTemperature.setText(_translate("ThermstUtil", "Set Cold Temperature"))
        self.actionRestorePresets.setText(_translate("ThermstUtil", "Restore Presets"))
        self.actionRestorePresets.setToolTip(_translate("ThermstUtil", "Restore Presets"))
        self.actionUserManual.setText(_translate("ThermstUtil", "User Manual"))
        self.actionAboutThermstUtil.setText(_translate("ThermstUtil", "About ThermstUtil"))
    def start_flask_server(self):
        self.flask_thread.start(QtCore.QThread.InheritPriority)

if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = Ui_ThermstUtil()
    window.setupUi(window)
    window.show()
    app.exec_()
    window.flask_thread.quit()
    sys.exit()
