# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/designerFiles/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(729, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.StatusArea = QtWidgets.QHBoxLayout()
        self.StatusArea.setObjectName("StatusArea")
        self.StatusMarker = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StatusMarker.setFont(font)
        self.StatusMarker.setObjectName("StatusMarker")
        self.StatusArea.addWidget(self.StatusMarker)
        self.OperationModeIcon = QtWidgets.QLabel(self.centralWidget)
        self.OperationModeIcon.setText("")
        self.OperationModeIcon.setPixmap(QtGui.QPixmap(":/icons/off.png"))
        self.OperationModeIcon.setObjectName("OperationModeIcon")
        self.StatusArea.addWidget(self.OperationModeIcon)
        self.StatusText = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StatusText.setFont(font)
        self.StatusText.setObjectName("StatusText")
        self.StatusArea.addWidget(self.StatusText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.StatusArea.addItem(spacerItem)
        self.StatusIcon = QtWidgets.QLabel(self.centralWidget)
        self.StatusIcon.setText("")
        self.StatusIcon.setPixmap(QtGui.QPixmap(":/icons/working.png"))
        self.StatusIcon.setObjectName("StatusIcon")
        self.StatusArea.addWidget(self.StatusIcon)
        self.SerialIndicatorIcon = QtWidgets.QLabel(self.centralWidget)
        self.SerialIndicatorIcon.setMaximumSize(QtCore.QSize(50, 32))
        self.SerialIndicatorIcon.setText("")
        self.SerialIndicatorIcon.setPixmap(QtGui.QPixmap(":/icons/serial_off.png"))
        self.SerialIndicatorIcon.setObjectName("SerialIndicatorIcon")
        self.StatusArea.addWidget(self.SerialIndicatorIcon)
        self.verticalLayout_4.addLayout(self.StatusArea)
        self.Separator = QtWidgets.QFrame(self.centralWidget)
        self.Separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.Separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separator.setObjectName("Separator")
        self.verticalLayout_4.addWidget(self.Separator)
        self.WorkArea = QtWidgets.QHBoxLayout()
        self.WorkArea.setObjectName("WorkArea")
        self.settingsBox = QtWidgets.QGroupBox(self.centralWidget)
        self.settingsBox.setEnabled(False)
        self.settingsBox.setMinimumSize(QtCore.QSize(300, 0))
        self.settingsBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.settingsBox.setLocale(QtCore.QLocale(QtCore.QLocale.Slovak, QtCore.QLocale.Slovakia))
        self.settingsBox.setObjectName("settingsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modeSelectorLayout = QtWidgets.QHBoxLayout()
        self.modeSelectorLayout.setObjectName("modeSelectorLayout")
        self.modeSelectorLabel = QtWidgets.QLabel(self.settingsBox)
        self.modeSelectorLabel.setObjectName("modeSelectorLabel")
        self.modeSelectorLayout.addWidget(self.modeSelectorLabel)
        self.modeSelectorHotButton = QtWidgets.QRadioButton(self.settingsBox)
        self.modeSelectorHotButton.setObjectName("modeSelectorHotButton")
        self.modeSelectorLayout.addWidget(self.modeSelectorHotButton)
        self.modeSelectorColdButton = QtWidgets.QRadioButton(self.settingsBox)
        self.modeSelectorColdButton.setChecked(True)
        self.modeSelectorColdButton.setObjectName("modeSelectorColdButton")
        self.modeSelectorLayout.addWidget(self.modeSelectorColdButton)
        self.verticalLayout.addLayout(self.modeSelectorLayout)
        self.setTemperatureLayout = QtWidgets.QHBoxLayout()
        self.setTemperatureLayout.setObjectName("setTemperatureLayout")
        self.temperatureLabel = QtWidgets.QLabel(self.settingsBox)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.setTemperatureLayout.addWidget(self.temperatureLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setTemperatureLayout.addItem(spacerItem1)
        self.temperatureInputBox = QtWidgets.QSpinBox(self.settingsBox)
        self.temperatureInputBox.setMinimum(-10)
        self.temperatureInputBox.setMaximum(50)
        self.temperatureInputBox.setProperty("value", 25)
        self.temperatureInputBox.setObjectName("temperatureInputBox")
        self.setTemperatureLayout.addWidget(self.temperatureInputBox)
        self.verticalLayout.addLayout(self.setTemperatureLayout)
        self.setMeasurementFrequencyLayout = QtWidgets.QHBoxLayout()
        self.setMeasurementFrequencyLayout.setObjectName("setMeasurementFrequencyLayout")
        self.freqMeasurementLabel = QtWidgets.QLabel(self.settingsBox)
        self.freqMeasurementLabel.setObjectName("freqMeasurementLabel")
        self.setMeasurementFrequencyLayout.addWidget(self.freqMeasurementLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setMeasurementFrequencyLayout.addItem(spacerItem2)
        self.freqMeasurementInputBox = QtWidgets.QSpinBox(self.settingsBox)
        self.freqMeasurementInputBox.setMinimum(500)
        self.freqMeasurementInputBox.setMaximum(10000)
        self.freqMeasurementInputBox.setProperty("value", 1000)
        self.freqMeasurementInputBox.setObjectName("freqMeasurementInputBox")
        self.setMeasurementFrequencyLayout.addWidget(self.freqMeasurementInputBox)
        self.verticalLayout.addLayout(self.setMeasurementFrequencyLayout)
        self.restorePresetsButton = QtWidgets.QPushButton(self.settingsBox)
        self.restorePresetsButton.setObjectName("restorePresetsButton")
        self.verticalLayout.addWidget(self.restorePresetsButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.CurrentTemperatureLabel = QtWidgets.QLabel(self.settingsBox)
        self.CurrentTemperatureLabel.setObjectName("CurrentTemperatureLabel")
        self.verticalLayout.addWidget(self.CurrentTemperatureLabel)
        self.temperatureDisplay = QtWidgets.QLabel(self.settingsBox)
        self.temperatureDisplay.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureDisplay.sizePolicy().hasHeightForWidth())
        self.temperatureDisplay.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 191, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 159, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 191, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 159, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 191, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 159, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 63, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.temperatureDisplay.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.temperatureDisplay.setFont(font)
        self.temperatureDisplay.setMouseTracking(True)
        self.temperatureDisplay.setAutoFillBackground(True)
        self.temperatureDisplay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.temperatureDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temperatureDisplay.setTextFormat(QtCore.Qt.PlainText)
        self.temperatureDisplay.setScaledContents(False)
        self.temperatureDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureDisplay.setObjectName("temperatureDisplay")
        self.verticalLayout.addWidget(self.temperatureDisplay, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.startButton = QtWidgets.QPushButton(self.settingsBox)
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.settingsBox)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.WorkArea.addWidget(self.settingsBox)
        self.graphBox = QtWidgets.QWidget(self.centralWidget)
        self.graphBox.setAutoFillBackground(True)
        self.graphBox.setObjectName("graphBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.graphBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphWidget = PlotWidget(self.graphBox)
        self.graphWidget.setAutoFillBackground(False)
        self.graphWidget.setObjectName("graphWidget")
        self.horizontalLayout_2.addWidget(self.graphWidget)
        self.WorkArea.addWidget(self.graphBox)
        self.verticalLayout_4.addLayout(self.WorkArea)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 729, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuConnect_Device = QtWidgets.QMenu(self.menuBar)
        self.menuConnect_Device.setObjectName("menuConnect_Device")
        mainWindow.setMenuBar(self.menuBar)
        self.actionStart = QtWidgets.QAction(mainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(mainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionRestorePresets = QtWidgets.QAction(mainWindow)
        self.actionRestorePresets.setObjectName("actionRestorePresets")
        self.actionUserManual = QtWidgets.QAction(mainWindow)
        self.actionUserManual.setObjectName("actionUserManual")
        self.actionAboutThermstUtil = QtWidgets.QAction(mainWindow)
        self.actionAboutThermstUtil.setObjectName("actionAboutThermstUtil")
        self.actionReadTemperature = QtWidgets.QAction(mainWindow)
        self.actionReadTemperature.setObjectName("actionReadTemperature")
        self.actionConnectDevice = QtWidgets.QAction(mainWindow)
        self.actionConnectDevice.setCheckable(False)
        self.actionConnectDevice.setEnabled(True)
        self.actionConnectDevice.setObjectName("actionConnectDevice")
        self.actionDisconnect_Device = QtWidgets.QAction(mainWindow)
        self.actionDisconnect_Device.setObjectName("actionDisconnect_Device")
        self.menuHelp.addAction(self.actionUserManual)
        self.menuHelp.addAction(self.actionAboutThermstUtil)
        self.menuConnect_Device.addAction(self.actionConnectDevice)
        self.menuConnect_Device.addAction(self.actionDisconnect_Device)
        self.menuBar.addAction(self.menuConnect_Device.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.startButton.clicked.connect(self.actionStart.trigger)
        self.stopButton.clicked.connect(self.actionStop.trigger)
        self.restorePresetsButton.clicked.connect(self.actionRestorePresets.trigger)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Thermal Stimulator"))
        self.StatusMarker.setText(_translate("mainWindow", "Status: "))
        self.OperationModeIcon.setToolTip(_translate("mainWindow", "Hot / Idle / Cold"))
        self.StatusText.setText(_translate("mainWindow", "Off"))
        self.StatusIcon.setToolTip(_translate("mainWindow", "Device did not inform an error"))
        self.SerialIndicatorIcon.setToolTip(_translate("mainWindow", "Serial comunication status"))
        self.settingsBox.setTitle(_translate("mainWindow", "Settings"))
        self.modeSelectorLabel.setText(_translate("mainWindow", "Mode:"))
        self.modeSelectorHotButton.setText(_translate("mainWindow", "Hot"))
        self.modeSelectorColdButton.setText(_translate("mainWindow", "Cold"))
        self.temperatureLabel.setText(_translate("mainWindow", "Temperature:"))
        self.temperatureInputBox.setSuffix(_translate("mainWindow", "ºC"))
        self.freqMeasurementLabel.setText(_translate("mainWindow", "Measurment Frecuency:"))
        self.freqMeasurementInputBox.setSuffix(_translate("mainWindow", " ms"))
        self.restorePresetsButton.setText(_translate("mainWindow", "Restore presets"))
        self.CurrentTemperatureLabel.setText(_translate("mainWindow", "Current Temperature:"))
        self.temperatureDisplay.setText(_translate("mainWindow", "--"))
        self.startButton.setText(_translate("mainWindow", "Start"))
        self.stopButton.setText(_translate("mainWindow", "Stop"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuConnect_Device.setTitle(_translate("mainWindow", "Connection"))
        self.actionStart.setText(_translate("mainWindow", "Start"))
        self.actionStop.setText(_translate("mainWindow", "Stop"))
        self.actionRestorePresets.setText(_translate("mainWindow", "Restore Presets"))
        self.actionRestorePresets.setToolTip(_translate("mainWindow", "Restore Presets"))
        self.actionUserManual.setText(_translate("mainWindow", "User Manual"))
        self.actionAboutThermstUtil.setText(_translate("mainWindow", "About ThermstUtil"))
        self.actionReadTemperature.setText(_translate("mainWindow", "ReadTemperature"))
        self.actionConnectDevice.setText(_translate("mainWindow", "Connect Device..."))
        self.actionDisconnect_Device.setText(_translate("mainWindow", "Disconnect Device"))

from pyqtgraph import PlotWidget
import resources_rc
